from .conversation import *
from .dairy_of_class import *
from .grade import *
from .message import *
from .pupil import *
from .subject_teacher import *
from .teacher import *
from .user import *
from .homework import *